using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Game_store.Migrations
{
    /// <inheritdoc />
    public partial class SeedFullVietnamWardsAndCommunes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Seed phường/xã/thị trấn cho các quận/huyện
            migrationBuilder.Sql(@"
                INSERT INTO ""Locations"" (""Country"", ""City"", ""District"", ""Ward"", ""Code"") VALUES
                -- HÀ NỘI - Quận Ba Đình
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Phúc Xá', 'HN-BD-PX'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Trúc Bạch', 'HN-BD-TB'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Vĩnh Phúc', 'HN-BD-VP'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Cống Vị', 'HN-BD-CV'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Liễu Giai', 'HN-BD-LG'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Nguyễn Trung Trực', 'HN-BD-NTT'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Quán Thánh', 'HN-BD-QT'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Ngọc Hà', 'HN-BD-NH'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Điện Biên', 'HN-BD-DB'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Đội Cấn', 'HN-BD-DC'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Ngọc Khánh', 'HN-BD-NK'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Kim Mã', 'HN-BD-KM'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Giảng Võ', 'HN-BD-GV'),
                ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phường Thành Công', 'HN-BD-TC'),

                -- HÀ NỘI - Quận Hoàn Kiếm
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Phan Chu Trinh', 'HN-HK-PCT'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Trống', 'HN-HK-HT'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Bồ', 'HN-HK-HB'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Bạc', 'HN-HK-HBA'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Gai', 'HN-HK-HG'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Buồm', 'HN-HK-HBU'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Đào', 'HN-HK-HD'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Mã', 'HN-HK-HM'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Chương Dương Độ', 'HN-HK-CDD'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Đồng Xuân', 'HN-HK-DX'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Lý Thái Tổ', 'HN-HK-LTT'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Tràng Tiền', 'HN-HK-TT'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Trần Hưng Đạo', 'HN-HK-THD'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Cửa Đông', 'HN-HK-CD'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Cửa Nam', 'HN-HK-CN'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Phúc Tân', 'HN-HK-PT'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Bông', 'HN-HK-HBO'),
                ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phường Hàng Bài', 'HN-HK-HBA2'),

                -- HÀ NỘI - Quận Đống Đa
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Cát Linh', 'HN-DD-CL'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Văn Miếu', 'HN-DD-VM'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Quốc Tử Giám', 'HN-DD-QTG'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Láng Thượng', 'HN-DD-LT'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Ô Chợ Dừa', 'HN-DD-OCD'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Văn Chương', 'HN-DD-VC'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Hàng Bột', 'HN-DD-HB'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Láng Hạ', 'HN-DD-LH'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Khâm Thiên', 'HN-DD-KT'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Thổ Quan', 'HN-DD-TQ'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Nam Đồng', 'HN-DD-ND'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Trung Phụng', 'HN-DD-TP'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Quang Trung', 'HN-DD-QT'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Trung Liệt', 'HN-DD-TL'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Phương Liên', 'HN-DD-PL'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Thịnh Quang', 'HN-DD-TQU'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Trung Tự', 'HN-DD-TTU'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Kim Liên', 'HN-DD-KL'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Phương Mai', 'HN-DD-PM'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Ngã Tư Sở', 'HN-DD-NTS'),
                ('Việt Nam', 'Hà Nội', 'Đống Đa', 'Phường Khương Thượng', 'HN-DD-KTH'),

                -- HÀ NỘI - Quận Hai Bà Trưng
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Nguyễn Du', 'HN-HBT-ND'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Bạch Đằng', 'HN-HBT-BD'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Phạm Đình Hổ', 'HN-HBT-PDH'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Lê Đại Hành', 'HN-HBT-LDH'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Đồng Nhân', 'HN-HBT-DN'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Phố Huế', 'HN-HBT-PH'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Đống Mác', 'HN-HBT-DM'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Thanh Lương', 'HN-HBT-TL'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Thanh Nhàn', 'HN-HBT-TN'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Cầu Dền', 'HN-HBT-CD'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Bách Khoa', 'HN-HBT-BK'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Đồng Tâm', 'HN-HBT-DT'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Vĩnh Tuy', 'HN-HBT-VT'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Bạch Mai', 'HN-HBT-BM'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Quỳnh Mai', 'HN-HBT-QM'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Quỳnh Lôi', 'HN-HBT-QL'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Minh Khai', 'HN-HBT-MK'),
                ('Việt Nam', 'Hà Nội', 'Hai Bà Trưng', 'Phường Trương Định', 'HN-HBT-TD'),

                -- HÀ NỘI - Quận Cầu Giấy
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Nghĩa Đô', 'HN-CG-ND'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Nghĩa Tân', 'HN-CG-NT'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Mai Dịch', 'HN-CG-MD'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Dịch Vọng', 'HN-CG-DV'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Dịch Vọng Hậu', 'HN-CG-DVH'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Quan Hoa', 'HN-CG-QH'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Yên Hòa', 'HN-CG-YH'),
                ('Việt Nam', 'Hà Nội', 'Cầu Giấy', 'Phường Trung Hòa', 'HN-CG-TH'),

                -- HỒ CHÍ MINH - Quận 1
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Tân Định', 'HCM-Q1-TD'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Đa Kao', 'HCM-Q1-DK'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Bến Nghé', 'HCM-Q1-BN'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Bến Thành', 'HCM-Q1-BT'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Nguyễn Thái Bình', 'HCM-Q1-NTB'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Phạm Ngũ Lão', 'HCM-Q1-PNL'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Cầu Ông Lãnh', 'HCM-Q1-COL'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Cô Giang', 'HCM-Q1-CG'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Nguyễn Cư Trinh', 'HCM-Q1-NCT'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Phường Cầu Kho', 'HCM-Q1-CK'),

                -- HỒ CHÍ MINH - Quận 3
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 01', 'HCM-Q3-P01'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 02', 'HCM-Q3-P02'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 03', 'HCM-Q3-P03'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 04', 'HCM-Q3-P04'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 05', 'HCM-Q3-P05'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 06', 'HCM-Q3-P06'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 07', 'HCM-Q3-P07'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 08', 'HCM-Q3-P08'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 09', 'HCM-Q3-P09'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 10', 'HCM-Q3-P10'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 11', 'HCM-Q3-P11'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 12', 'HCM-Q3-P12'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 13', 'HCM-Q3-P13'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Phường 14', 'HCM-Q3-P14'),

                -- HỒ CHÍ MINH - Quận 5
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 01', 'HCM-Q5-P01'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 02', 'HCM-Q5-P02'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 03', 'HCM-Q5-P03'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 04', 'HCM-Q5-P04'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 05', 'HCM-Q5-P05'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 06', 'HCM-Q5-P06'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 07', 'HCM-Q5-P07'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 08', 'HCM-Q5-P08'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 09', 'HCM-Q5-P09'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 10', 'HCM-Q5-P10'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 11', 'HCM-Q5-P11'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 12', 'HCM-Q5-P12'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 13', 'HCM-Q5-P13'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 14', 'HCM-Q5-P14'),
                ('Việt Nam', 'Hồ Chí Minh', 'Quận 5', 'Phường 15', 'HCM-Q5-P15'),

                -- ĐÀ NẴNG - Quận Hải Châu
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Thạch Thang', 'DN-HC-TT'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Hải Châu I', 'DN-HC-HC1'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Hải Châu II', 'DN-HC-HC2'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Phước Ninh', 'DN-HC-PN'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Hòa Thuận Tây', 'DN-HC-HTT'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Hòa Thuận Đông', 'DN-HC-HTD'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Nam Dương', 'DN-HC-ND'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Bình Hiên', 'DN-HC-BH'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Bình Thuận', 'DN-HC-BT'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Hòa Cường Bắc', 'DN-HC-HCB'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Hòa Cường Nam', 'DN-HC-HCN'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Thanh Bình', 'DN-HC-TB'),
                ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Phường Thuận Phước', 'DN-HC-TP'),

                -- ĐÀ NẴNG - Quận Thanh Khê
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Tam Thuận', 'DN-TK-TT'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Thanh Khê Tây', 'DN-TK-TKT'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Thanh Khê Đông', 'DN-TK-TKD'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Xuân Hà', 'DN-TK-XH'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Tân Chính', 'DN-TK-TC'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Chính Gián', 'DN-TK-CG'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Vĩnh Trung', 'DN-TK-VT'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Thạc Gián', 'DN-TK-TG'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường An Khê', 'DN-TK-AK'),
                ('Việt Nam', 'Đà Nẵng', 'Thanh Khê', 'Phường Hòa Khê', 'DN-TK-HK'),

                -- HẢI PHÒNG - Quận Hồng Bàng
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Quán Toan', 'HP-HB-QT'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Hùng Vương', 'HP-HB-HV'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Sở Dầu', 'HP-HB-SD'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Thượng Lý', 'HP-HB-TL'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Hạ Lý', 'HP-HB-HL'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Minh Khai', 'HP-HB-MK'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Trại Chuối', 'HP-HB-TC'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Hoàng Văn Thụ', 'HP-HB-HVT'),
                ('Việt Nam', 'Hải Phòng', 'Hồng Bàng', 'Phường Phan Bội Châu', 'HP-HB-PBC'),

                -- CẦN THƠ - Quận Ninh Kiều
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường Cái Khế', 'CT-NK-CK'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Hòa', 'CT-NK-AH'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường Thới Bình', 'CT-NK-TB'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Nghiệp', 'CT-NK-AN'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Cư', 'CT-NK-AC'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Lạc', 'CT-NK-AL'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Phú', 'CT-NK-AP'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường Xuân Khánh', 'CT-NK-XK'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường Hưng Lợi', 'CT-NK-HL'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Khánh', 'CT-NK-AKH'),
                ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Phường An Bình', 'CT-NK-AB'),

                -- Các tỉnh thành khác - Thêm phường/xã chính
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Bạch Đằng', 'QN-HL-BD'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Hồng Gai', 'QN-HL-HG'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Hà Khánh', 'QN-HL-HK'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Cao Xanh', 'QN-HL-CX'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Giếng Đáy', 'QN-HL-GD'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Hà Phong', 'QN-HL-HP'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Hà Khắc', 'QN-HL-HKH'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Cao Thắng', 'QN-HL-CT'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Hùng Thắng', 'QN-HL-HT'),
                ('Việt Nam', 'Quảng Ninh', 'Hạ Long', 'Phường Yết Kiêu', 'QN-HL-YK'),

                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vĩnh Hòa', 'KH-NT-VH'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vĩnh Phước', 'KH-NT-VP'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vạn Thắng', 'KH-NT-VT'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vạn Thạnh', 'KH-NT-VTH'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phương Sài', 'KH-NT-PS'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phương Sơn', 'KH-NT-PSO'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phước Hòa', 'KH-NT-PH'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phước Tiến', 'KH-NT-PT'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Tân Lập', 'KH-NT-TL'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Lộc Thọ', 'KH-NT-LT'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Ngọc Hiệp', 'KH-NT-NH'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vĩnh Nguyên', 'KH-NT-VN'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vĩnh Trường', 'KH-NT-VTR'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Xương Huân', 'KH-NT-XH'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Vĩnh Thọ', 'KH-NT-VTO'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phước Tân', 'KH-NT-PTA'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phước Hải', 'KH-NT-PHA'),
                ('Việt Nam', 'Khánh Hòa', 'Nha Trang', 'Phường Phước Long', 'KH-NT-PL'),

                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Hiệp Thành', 'BD-TDM-HT'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Phú Lợi', 'BD-TDM-PL'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Phú Cường', 'BD-TDM-PC'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Phú Hòa', 'BD-TDM-PH'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Phú Thọ', 'BD-TDM-PT'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Chánh Nghĩa', 'BD-TDM-CN'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Định Hòa', 'BD-TDM-DH'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Hoà Phú', 'BD-TDM-HP'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Phú Mỹ', 'BD-TDM-PM'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Phú Tân', 'BD-TDM-PTA'),
                ('Việt Nam', 'Bình Dương', 'Thủ Dầu Một', 'Phường Tân An', 'BD-TDM-TA'),

                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Trảng Dài', 'DNI-BH-TD'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Phong', 'DNI-BH-TP'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Biên', 'DNI-BH-TB'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Hố Nai', 'DNI-BH-HN'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Hòa', 'DNI-BH-TH'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Hiệp', 'DNI-BH-THI'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Bửu Long', 'DNI-BH-BL'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Tiến', 'DNI-BH-TT'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tam Hiệp', 'DNI-BH-THIE'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Long Bình', 'DNI-BH-LB'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Quang Vinh', 'DNI-BH-QV'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Mai', 'DNI-BH-TM'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Thống Nhất', 'DNI-BH-TN'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Trung Dũng', 'DNI-BH-TDU'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tam Hòa', 'DNI-BH-THO'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Hòa Bình', 'DNI-BH-HB'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Quyết Thắng', 'DNI-BH-QT'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Thanh Bình', 'DNI-BH-TBI'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Bình Đa', 'DNI-BH-BD'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường An Bình', 'DNI-BH-AB'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Bửu Hòa', 'DNI-BH-BHO'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Long Bình Tân', 'DNI-BH-LBT'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Vạn', 'DNI-BH-TV'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tân Hạnh', 'DNI-BH-THA'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Hiệp Hòa', 'DNI-BH-HH'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Hóa An', 'DNI-BH-HA'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường An Hòa', 'DNI-BH-AH'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Tam Phước', 'DNI-BH-TPA'),
                ('Việt Nam', 'Đồng Nai', 'Biên Hòa', 'Phường Phước Tân', 'DNI-BH-PTA');
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DELETE FROM ""Locations"" WHERE ""Ward"" IS NOT NULL;");
        }
    }
}
